### ISSUE TITLE
Multiple layers of bubbles

### ISSUE THREAD

**Issue by leanneallen** [rmarmito/BubbleMachine#10]
Be able to add multiple bubble layers

**Checklist**
- [x] Determine layer maximum
- [x] Add button to add layer
- [x] Bubbles adjust height according to number of layers

**Related**

**Comment by jambho** [comment]
Current layer max has been decided at 6 until further discussion

**Comment by jambho** [comment]
Layer max changed to 3, new layer table created when an entry with said layer has been submitted.
