### ISSUE TITLE
Backend set up

### ISSUE THREAD

**Issue by leanneallen** [rmarmito/BubbleMachine#15]
Get Django REST API set up

**Checklist**
- [x] virtualenv working
- [x] Prepped to be ready to use, if needed

**Related**
[Django REST](https://www.django-rest-framework.org/)

**Comment by leanneallen** [comment]
@jambho configured backend for instance of needing it

**Comment by jambho** [comment]
Backend ready for use, use case needs to be decided and hosting service transitioned
