### ISSUE TITLE
Bubble creation with button

### ISSUE THREAD

**Issue by leanneallen** [rmarmito/BubbleMachine#9]
Be able to create and edit bubble with a button

**Checklist**

- [x] #19
- [x] Button allows for bubble to be created on horizontal axis
- [ ] Allow bubble length to be edited (NOTE: aim for using separate, draggable scrubber to edit bubble length like discussed in CDR -- if not feasible in sprint will move to next)
- [x] Be able to create multiple bubbles that do not overlap
- [x] Ellipses maintain proper height

**Related**
#3

**Comment by jambho** [comment]
Bubble creation done, needs additional work with waveform to allow intuitive scrubbing.
